### ISSUE TITLE
Section 3.1.1. Question: How to invoke function with an Option None

### ISSUE THREAD

**Issue by edandresvan** [brndnmtthws/rust-design-patterns-book#3]
Hi Brenden, 

At the beginning of section 3.1.1, we learn about simple pattern matching with the generic function `some_or_none<T>()`. I would like to know how to pass a None value to the function. Currently, in my code I wrap a data type in an Option enum and then pass the None value: 

```rust
fn some_or_none<T>(value: &Option<T>) {
  match value {
    Some(_v) => println!("Option has some value."),
    None => println!("Option does not value."),
  }
}

some_or_none(&Some("ABC"));
some_or_none(&Option::<String>::None);
```

Thanks for your help.

**Comment by brndnmtthws** [comment]
Your code is certainly fine.  Another way to do it would be like this:

```rust
some_or_none::<String>(&None);
```

As you might notice, you still need to define some kind of type for the option, which above is `String`. Let's look at the enum definition for `Option<T>`:

```rust
pub enum Option<T> {
    None,
    Some(T),
}
```

Note how we have this type `T` as a type parameter, and it needs to be specified. It's true that the `None` in the enum doesn't have a type associated with it, but it doesn't matter because the enum itself still needs a type (there's no optional type parameters, not yet at least). Additionally, the Rust compiler wants to know how bytes are needed for the underlying data structure at compile time, and due to the complexities involved in calculating that, it's just much easier to require all parameters are specified.

[Here's a Rust playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3de7b3b52f4095f3ffba923f73340fe6).

**Comment by edandresvan** [comment]
Thank you, Brenden.
